# Generated by Django 3.0.3 on 2020-04-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('NONE', 'None'), ('TASTE', 'Taste loss'), ('COLD', 'Cold'), ('COUGH', 'Cough'), ('FEVER', 'Fever'), ('RESPIRATORY', 'Respitatory difficulties'), ('THROAT', 'Throat soreness')], default='NONE', max_length=11)),
            ],
        ),
        migrations.AlterField(
            model_name='commorbidity',
            name='name',
            field=models.CharField(choices=[('NONE', 'None'), ('DIABETES', 'Diabetes'), ('PRESSURE', 'High blood pressure'), ('HEART', 'Heart Disease'), ('LUNG', 'Lung Disease'), ('CANCER', 'Cancer')], default='NONE', max_length=11),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='commorbidities',
        ),
        migrations.AddField(
            model_name='customuser',
            name='commorbidities',
            field=models.ManyToManyField(to='main.Commorbidity'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='household_size',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='symptoms',
            field=models.ManyToManyField(to='main.Symptom'),
        ),
    ]
