# Generated by Django 3.0.3 on 2020-04-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200404_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commorbidity',
            name='name',
            field=models.CharField(choices=[('NONE', 'None'), ('DIABETES', 'Diabetes'), ('PRESSURE', 'High blood pressure'), ('HEART', 'Heart Disease'), ('LUNG', 'Lung Disease'), ('CANCER', 'Cancer')], default='NONE', max_length=200),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='name',
            field=models.CharField(choices=[('NONE', 'None'), ('TASTE', 'Taste loss'), ('COLD', 'Cold'), ('COUGH', 'Cough'), ('FEVER', 'Fever'), ('RESPIRATORY', 'Respitatory difficulties'), ('THROAT', 'Throat soreness')], default='NONE', max_length=200),
        ),
    ]
