# Generated by Django 3.0.3 on 2020-04-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200405_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='last_hand_wash',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='last hand wash'),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='last_leave',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='last household leave'),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='last_physical_activity',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='last physical activity'),
        ),
    ]
