# Generated by Django 3.0.3 on 2020-04-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_logentry_outingreason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='crowded_places',
            field=models.BooleanField(blank=True, choices=[('n', 'No'), ('y', 'Yes')], default='n', null=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='hand_wash_after_leave',
            field=models.BooleanField(blank=True, choices=[('n', 'No'), ('y', 'Yes')], default='y', null=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='hand_wash_frequency',
            field=models.CharField(choices=[('D', '0 times'), ('L', 'Between 1 and 3 times'), ('M', 'Between 3 and 5 times'), ('H', '6 times or more')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='leave',
            field=models.BooleanField(choices=[('n', 'No'), ('y', 'Yes')], default='n'),
        ),
    ]
