# Generated by Django 3.0.3 on 2020-04-06 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200406_1109'),
        ('main', '0009_auto_20200406_1305'),
    ]

    operations = [
    ]
